# CI/CD Docker Website => Build & Push to DockerHub

name: Web site > Build & Push
# Trigger
on:
  # Push ou Pull Request on @main
  push:
    branches: [ main ] 

# Start Jobs
jobs:
  configuration: # Environnement config
    runs-on: ubuntu-latest
    steps:

    # Checkout du repo
    - name: Checkout App Code
      uses: actions/checkout@v3

    # Login to DockerHub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Setup BuildKit builder
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Build & Push website
    - name: Build and push website
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/static-website:latest